name: Samba

services:
  samba:
    container_name: ${SAMBA_CONTAINER_NAME}
    hostname: ${SAMBA_CONTAINER_NAME}
    image: crazymax/samba:${SAMBA_IMAGE_VERSION}
    restart: unless-stopped
    cap_add:
      - CAP_NET_ADMIN
      - CAP_NET_RAW
    env_file:
      - samba.env
    environment:
      - CONFIG_FILE=/config/config.yaml
    network_mode: host
    volumes:
      - ./cache:/data
      - ./config:/config
    healthcheck:
      disable: true
