secrets:
  ludelafo_password.txt:
    file: ./config/ludelafo_password.txt

  heaspery_password.txt:
    file: ./config/heaspery_password.txt

services:
  samba:
    volumes:
      - ./shares/private:/shares/private
      - ./shares/public:/shares/public
    labels:
      ## Glance
      - glance.name=Samba
      # https://github.com/glanceapp/glance/blob/main/docs/configuration.md#icons
      - glance.icon=mdi:folder-network
      - glance.url=smb://${SAMBA_FQDN}
      - glance.description=Re-implementation of the SMB networking protocol.
      - glance.category=infrastructure
