@startnwdiag raspberry-pi-diagram
!include <office/Devices/router>
!include <office/Servers/cluster_server>
!include <office/Servers/application_server>
!include <office/Servers/virtual_application_server>

nwdiag {
  network internal {
      address = "192.168.1.x/24"

      raspberry_pi [address = "192.168.1.254"];
  }

  raspberry_pi [description = "<$cluster_server>\n Raspberry Pi 3\n pi.m3w.ch"]

  network host {
    raspberry_pi

    technitium
    traefik
  }

  technitium [description = "<$virtual_application_server>\n Technitium\n (DNS server)\n https://technitium.pi.m3w.ch"]
  traefik [description = "<$virtual_application_server>\n Traefik\n (Reverse proxy)\n https://traefik.pi.m3w.ch"];

  network traefik_network {
    address = "<Docker internal network>"
  
    glance
    traefik
    wg_easy
  }

  glance [description = "<$virtual_application_server>\n Glance\n (Dashboard)\n https://pi.m3w.ch"]
  wg_easy [description = "<$virtual_application_server>\n Wireguard Easy\n (VPN)\n https://wg.pi.m3w.ch"]
}
@endnwdiag
