@startnwdiag raspberry-pi-diagram
!include <office/Concepts/application_generic>
!include <office/Servers/server_generic>

nwdiag {
  network internal {
      address = "192.168.1.x/24"

      raspberry_pi [address = "192.168.1.254"]
  }

  raspberry_pi [description = "<$server_generic>\n Raspberry Pi 3\n raspberry.m3w.ch"]

  network {
    raspberry_pi

    tang
  }

  tang [description = "<$application_generic>\n Tang\n (LUKS unlocker)\n http://192.168.1.254"]
}
@endnwdiag
