@startnwdiag nas-architecture
!include <office/Servers/application_server>
!include <office/Servers/virtual_application_server>

title NAS architecture

nwdiag {
  network internal {
      address = "192.168.1.x/24"

      nas [address = "192.168.1.2"];
  }

  nas[description = "<$application_server>\nNAS\nnas.m3w.ch"]
  
  adguard_home [description = "<$virtual_application_server>\nAdGuard Home\n(DNS and DHCP server)\nhttps://adguard.m3w.ch"]
  authentik [description = "<$virtual_application_server>\nAuthentik ?\n(Authentification)\nhttps://authentik.m3w.ch"]
  backrest [description = "<$virtual_application_server>\nBackrest ?\n(Backups)\nhttps://beszel.m3w.ch"]
  beszel [description = "<$virtual_application_server>\nBeszel\n(Hardware monitoring)\nhttps://beszel.m3w.ch"]
  gatus [description = "<$virtual_application_server>\nGatus\n(Service monitoring)\nhttps://gatus.m3w.ch"]
  glance_ludelafo [description = "<$virtual_application_server>\nGlance (ludelafo)\n(Dashboard)\nhttps://ludelafo.m3w.ch"]
  glance_heaspery [description = "<$virtual_application_server>\nGlance (heaspery)\n(Dashboard)\nhttps://heaspery.m3w.ch"]
  navidrome [description = "<$virtual_application_server>\nNavidrome\n(Music server)\nhttps://navidrome.m3w.ch"]
  qbittorrent [description = "<$virtual_application_server>\nqBittorrent\n(Torrent client)\nhttps://qbittorrent.m3w.ch"]
  samba [description = "<$virtual_application_server>\nSamba\n(Network shares)\nsmb://192.168.1.2"]
  syncthing_ludelafo [description = "<$virtual_application_server>\nSyncthing (ludelafo)\n(Files synchronisation)\nhttps://syncthing.ludelafo.m3w.ch"]
  syncthing_heaspery [description = "<$virtual_application_server>\nSyncthing (heaspery)\n(Files synchronisation)\nhttps://syncthing.heaspery.m3w.ch"]
  traefik [description = "<$virtual_application_server>\nTraefik\n(Reverse proxy)\nhttps://traefik.m3w.ch"];
  wg_easy [description = "<$virtual_application_server>\nWireguard Easy\n(VPN)\nhttps://vpn.m3w.ch"]

  network host {
    nas

    adguard_home [address = ":53/tcp+udp, :67/udp, :68/udp, ..."]
    samba [address = ":445, ..."]
    traefik [address = ":80, :443"]
  }

  network traefik_network {
    address = "<Docker internal network>"

    traefik
  }

  network traefik_network {
    address = "<Docker internal network>"

    authentik
    backrest
    beszel
  }

  network traefik_network {
    address = "<Docker internal network>"

    gatus
    glance_ludelafo
    glance_heaspery
  }

  network traefik_network {
    address = "<Docker internal network>"

    navidrome
    qbittorrent
    wg_easy
  }

  network traefik_network {
    address = "<Docker internal network>"

    syncthing_ludelafo
    syncthing_heaspery
  }
}
@endnwdiag
