name: Authelia

networks:
  lldap_network:
    external: true
  traefik_network:
    external: true

secrets:
  JWT_SECRET:
    file: ./secrets/JWT_SECRET
  SESSION_SECRET:
    file: ./secrets/SESSION_SECRET
  STORAGE_PASSWORD:
    file: ./secrets/STORAGE_PASSWORD
  STORAGE_ENCRYPTION_KEY:
    file: ./secrets/STORAGE_ENCRYPTION_KEY

services:
  authelia:
    container_name: ${AUTHELIA_CONTAINER_NAME}
    hostname: ${AUTHELIA_CONTAINER_NAME}
    image: authelia/authelia:${AUTHELIA_IMAGE_VERSION}
    command:
      - authelia
      - --config=/config/configuration.yaml
    restart: unless-stopped
    env_file:
      - authelia.env
    environment:
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/run/secrets/JWT_SECRET
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/SESSION_SECRET
      - AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE=/run/secrets/STORAGE_PASSWORD
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/STORAGE_ENCRYPTION_KEY
    networks:
      - lldap_network
      - traefik_network
    expose:
      - 9091
    volumes:
      - ./config:/config
    labels:
      ## Traefik
      - traefik.enable=true
      # Router
      - traefik.http.routers.${AUTHELIA_CONTAINER_NAME}.entryPoints=websecure
      - traefik.http.routers.${AUTHELIA_CONTAINER_NAME}.rule=Host(`${AUTHELIA_FQDN}`)
      # Service
      - traefik.http.services.${AUTHELIA_CONTAINER_NAME}.loadbalancer.server.port=9091
      # Middleware
      - traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/authz/forward-auth
      - traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardAuth.maxResponseBodySize=8192
      - traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email,Remote-Name
