- name: Configure Proxmox instance
  hosts: localhost
  become: true
  tasks:
    ## Updates and packages
    - name: Download Proxmox GPG key
      ansible.builtin.get_url:
        url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
        dest: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
        mode: "0644"

    - name: Calculate Proxmox GPG key checksum
      ansible.builtin.stat:
        path: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
        checksum_algorithm: sha512
      register: proxmox_gpg_key

    - name: Verify Proxmox GPG key checksum
      ansible.builtin.fail:
        msg: "Proxmox GPG key checksum does not match expected value."
      when:
        proxmox_gpg_key.stat.checksum !=
        "7da6fe34168adc6e479327ba517796d4702fa2f8b4f0a9833f5ea6e6b48f6507a6da403a274fe201595edc86a84463d50383d07f64bdde2e3658108db7d6dc87"

    - name: Add Proxmox APT repository
      ansible.builtin.apt_repository:
        repo:
          "deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm
          pve-no-subscription"
        filename: pve-install-repo
        state: present

    - name: Upgrade the OS
      ansible.builtin.apt:
        upgrade: full
        autoclean: true
        autoremove: true

    - name: Install Proxmox packages
      ansible.builtin.apt:
        pkg:
          - chrony
          - open-iscsi
          - postfix
          - proxmox-default-kernel
          - proxmox-ve

    - name: Remove Proxmox conflicting packages
      ansible.builtin.apt:
        name:
          - "linux-image-6.1*"
          - linux-image-amd64
          - os-prober
        state: absent

    - name: Install additional packages
      ansible.builtin.apt:
        pkg:
          - ansible
          - git

    ## Network configuration
    - name: Configure /etc/hosts
      ansible.builtin.template:
        src: etc-hosts.j2
        dest: /etc/hosts
        mode: "0644"
      vars:
        ip_address: "{{ lan0_ip_address }}"

    - name: Configure /etc/hostname
      ansible.builtin.template:
        src: etc-hostname.j2
        dest: /etc/hostname
        mode: "0644"

    - name: Configure /etc/network/interfaces
      ansible.builtin.template:
        src: etc-network-interfaces.j2
        dest: /etc/network/interfaces
        mode: "0644"

    - name: Configure interface name for lan0 network
      ansible.builtin.template:
        src: etc-systemd-network-persistent-link.link.j2
        dest: /etc/systemd/network/10-lan0-persistent-link.link
        mode: "0644"
      vars:
        interface_name: "{{ lan0_interface_name }}"
        mac_address: "{{ lan0_mac_address }}"

    - name: Configure interface name for lan1 network
      ansible.builtin.template:
        src: etc-systemd-network-persistent-link.link.j2
        dest: /etc/systemd/network/11-lan1-persistent-link.link
        mode: "0644"
      vars:
        interface_name: "{{ lan1_interface_name }}"
        mac_address: "{{ lan1_mac_address }}"

    ## Disks
    - name: Create the systemd mount unit file
      when: disk_label != None
      ansible.builtin.template:
        src: etc-systemd-system-mnt-pve-disk.mount.j2
        dest: /etc/systemd/system/mnt-pve-{{ disk_label }}.mount
        mode: "0644"

    - name: Enable and start the systemd mount unit
      when: disk_label != None
      ansible.builtin.systemd:
        name: mnt-pve-{{ disk_label }}.mount
        state: started
        daemon_reload: true
        enabled: true

    ## Container configuration
    - name: Mount the disk to the container
      when: disk_label != None
      ansible.builtin.lineinfile:
        path: /etc/pve/lxc/{{ lxc_id }}.conf
        line:
          "mp0: /mnt/pve/{{ disk_label }},mp=/home/{{ user
          }},mountoptions=noatime,backup=0"

    - name: Enable nesting feature for using Docker in the container
      when: lxc_id != None
      ansible.builtin.lineinfile:
        path: /etc/pve/lxc/{{ lxc_id }}.conf
        line: "features: nesting=1"

    - name: Enable start on boot
      when: lxc_id != None
      ansible.builtin.lineinfile:
        path: /etc/pve/lxc/{{ lxc_id }}.conf
        line: "onboot: 1"

    # # Source: https://github.com/portainer/portainer/issues/8478#issuecomment-1426866713
    # - name: Clear the cap drops
    #   ansible.builtin.lineinfile:
    #     path: /etc/pve/lxc/{{ lxc_id }}.conf
    #     line: 'lxc.cap.drop:'
