name: Technitium

networks:
  technitium_network:
    name: technitium_network
    driver: macvlan
    driver_opts:
      parent: ${MACVLAN_NETWORK_INTERFACE}
    ipam:
      driver: default
      config:
        - subnet: ${MACVLAN_NETWORK_SUBNET}
          gateway: ${MACVLAN_NETWORK_GATEWAY}

secrets:
  technitium_password:
    file: ./technitium_password.txt

volumes:
  technitium_data:
    name: technitium_data

services:
  technitium:
    container_name: ${TECHNITIUM_CONTAINER_NAME}
    image: technitium/dns-server:${TECHNITIUM_VERSION}
    restart: unless-stopped
    env_file:
      - technitium.env
    # As this container uses a MACVLAN network, ports do not need to be published.
    networks:
      technitium_network:
        interface_name: wlan0
        gw_priority: 1
        # ipv4_address: ${MACVLAN_NETWORK_IP}
    secrets:
      - technitium_password
    volumes:
      - technitium_data:/etc/dns
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
