networks:
  traefik_network:
    external: true

services:
  technitium:
    networks:
      traefik_network:
        gw_priority: 0
    expose:
      - 5380
    labels:
      ## Traefik
      - traefik.enable=true
      # Router
      - traefik.http.routers.${TECHNITIUM_CONTAINER_NAME}.entryPoints=websecure
      - traefik.http.routers.${TECHNITIUM_CONTAINER_NAME}.rule=Host(`${TECHNITIUM_FQDN}`)
      # Service
      - traefik.http.services.${TECHNITIUM_CONTAINER_NAME}.loadbalancer.server.port=5380
      ## Glance
      - glance.name=Technitium
      # https://github.com/glanceapp/glance/blob/main/docs/configuration.md#icons
      - glance.icon=sh:technitium
      - glance.url=https://${TECHNITIUM_FQDN}
      - glance.description=DNS server with advanced features and a web console.
      - glance.category=infrastructure
