name: Traefik

networks:
  traefik_network:
    name: traefik_network

secrets:
  infomaniak_access_token.txt:
    file: ./data/infomaniak_access_token.txt

services:
  traefik:
    container_name: ${TRAEFIK_CONTAINER_NAME}
    hostname: ${TRAEFIK_CONTAINER_NAME}
    image: traefik:${TRAEFIK_IMAGE_VERSION}
    command:
      - --configFile=/etc/traefik/traefik_static.yaml
    restart: unless-stopped
    environment:
      - INFOMANIAK_ACCESS_TOKEN_FILE=/run/secrets/infomaniak_access_token.txt
    networks:
      - traefik_network
    ports:
      - 80:80
      - 443:443
      - 25565:25565
    secrets:
      - infomaniak_access_token.txt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/acme.json:/var/lib/traefik/acme.json
      - ./config/traefik_static.yaml:/etc/traefik/traefik_static.yaml:ro
      - ./config/traefik_dynamic.yaml:/etc/traefik/traefik_dynamic.yaml:ro
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      start_period: 5s
      interval: 120s
    labels:
      ## Traefik
      - traefik.enable=true
      # Router
      - traefik.http.routers.${TRAEFIK_CONTAINER_NAME}.entryPoints=websecure
      - traefik.http.routers.${TRAEFIK_CONTAINER_NAME}.rule=Host(`${TRAEFIK_FQDN}`)
      # Service
      - traefik.http.routers.${TRAEFIK_CONTAINER_NAME}.service=api@internal
      ## Pocket ID
      - traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.Secret=${TRAEFIK_OIDC_SECRET}
      - traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.Provider.Url=https://auth.m3w.ch
      - traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.Provider.ClientId=${TRAEFIK_OIDC_CLIENT_ID}
      - traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.Provider.ClientSecret=${TRAEFIK_OIDC_CLIENT_SECRET}
      - traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.Provider.UsePkce=true
      - traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.Scopes=openid,profile,email
