name: Traefik

networks:
  traefik_network:
    name: traefik_network

secrets:
  infomaniak_access_token.txt:
    file: ./config/infomaniak_access_token.txt

services:
  traefik:
    container_name: ${TRAEFIK_CONTAINER_NAME}
    hostname: ${TRAEFIK_CONTAINER_NAME}
    image: traefik:${TRAEFIK_IMAGE_VERSION}
    command:
      - --configFile=/etc/traefik/traefik_static.yaml
    restart: unless-stopped
    environment:
      - INFOMANIAK_ACCESS_TOKEN_FILE=/run/secrets/infomaniak_access_token.txt
    networks:
      - traefik_network
    ports:
      - 80:80
      - 443:443
      - 25565:25565
    secrets:
      - infomaniak_access_token.txt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/acme.json:/var/lib/traefik/acme.json
      - ./traefik_static.yaml:/etc/traefik/traefik_static.yaml:ro
      - ./traefik_dynamic.yaml:/etc/traefik/traefik_dynamic.yaml:ro
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      start_period: 5s
      interval: 120s
    labels:
      ## Traefik
      - traefik.enable=true
      # Router
      - traefik.http.routers.${TRAEFIK_CONTAINER_NAME}.entryPoints=websecure
      - traefik.http.routers.${TRAEFIK_CONTAINER_NAME}.rule=Host(`${TRAEFIK_FQDN}`)
      - traefik.http.routers.${TRAEFIK_CONTAINER_NAME}-ping.entryPoints=websecure
      - traefik.http.routers.${TRAEFIK_CONTAINER_NAME}-ping.rule=(Host(`localhost`) || Host(`${TRAEFIK_FQDN}`)) && PathPrefix(`/ping`)
      # Service
      - traefik.http.routers.${TRAEFIK_CONTAINER_NAME}.service=api@internal
      - traefik.http.routers.${TRAEFIK_CONTAINER_NAME}-ping.service=ping@internal
