http:
  routers:
    router:
      rule: "Host(`syncthing.m3w.ch`)"
      entryPoints:
        - "websecure"
      service: router

  services:
    router:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "http://192.168.1.2:8384"

  middlewares:
    http-strict-transport-security-header:
      headers:
        customResponseHeaders:
          Strict-Transport-Security: max-age=63072000; includeSubDomains

tls:
  options:
    default:
      minVersion: VersionTLS12
      curvePreferences:
        - X25519
        - CurveP256
        - CurveP384
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
