name: Tinyauth

networks:
  lldap_network:
    external: true
  traefik_network:
    external: true

services:
  tinyauth:
    container_name: ${TINYAUTH_CONTAINER_NAME}
    hostname: ${TINYAUTH_CONTAINER_NAME}
    image: ghcr.io/steveiliop56/tinyauth:${TINYAUTH_IMAGE_VERSION}
    restart: unless-stopped
    env_file:
      - tinyauth.env
    environment:
      - TINYAUTH_APPURL=https://${TINYAUTH_FQDN}
      - TINYAUTH_LDAP_ADDRESS=ldap://lldap:3890
      - TINYAUTH_LDAP_SEARCHFILTER=(uid=%s)
      - TINYAUTH_LDAP_INSECURE=true
    networks:
      - traefik_network
    expose:
      - 3000
    labels:
      ## Traefik
      - traefik.enable=true
      # Router
      - traefik.http.routers.${TINYAUTH_CONTAINER_NAME}.entryPoints=websecure
      - traefik.http.routers.${TINYAUTH_CONTAINER_NAME}.rule=Host(`${TINYAUTH_FQDN}`)
      # Service
      - traefik.http.services.${TINYAUTH_CONTAINER_NAME}.loadbalancer.server.port=3000
      # Middleware
      - traefik.http.middlewares.tinyauth.forwardauth.address=http://tinyauth:3000/api/auth/traefik
