services:
  dynacat:
    container_name: ${DYNACAT_CONTAINER_NAME}
    image: panonim/dynacat:${DYNACAT_VERSION}
    restart: unless-stopped
    env_file:
      - dynacat.env
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/app/config:ro
