auth:
  - user: ${USER}
    group: ${GROUP}
    uid: ${PUID}
    gid: ${PGID}
    password_file: /run/secrets/user_password

global:
  - "access based share enum = yes"

share:
  - name: common
    comment: Common
    path: /shares/common
    browsable: yes
    readonly: yes
    guest ok: yes
    veto: no
    # Uncomment this line to enable recycle bin
    # recycle: yes
