auth:
  - user: ${USER}
    group: ${GROUP}
    uid: ${PUID}
    gid: ${PGID}
    password_file: /run/secrets/user_password

global:
  - "access based share enum = yes"

share:
  - name: public
    comment: Public
    path: /shares/public
    writelist: ${USER}
    browsable: yes
    readonly: yes
    guestok: yes
    veto: no
    # Uncomment this line to enable recycle bin
    # recycle: yes

  - name: private
    comment: Private
    path: /shares/private
    writelist: ${USER}
    browsable: yes
    readonly: no
    guestok: no
    veto: no
    # Uncomment this line to enable recycle bin
    # recycle: yes
