user: ludelafo
user_id: 1000
group: ludelafo
group_id: 1000

hostname: ludelafo
domain: m3w.ch

interface_name: lan0
interface_mac_address: "bc:24:11:45:83:93"
interface_ip_address: 192.168.1.3
interface_netmask: 255.255.255.0
interface_gateway: 192.168.1.1

dropbear_ssh_port: 2222
