name: AdGuard Home

networks:
  adguard_home_network:
    name: adguard_home_network
    driver: macvlan
    driver_opts:
      parent: ${MACVLAN_NETWORK_INTERFACE}
    ipam:
      driver: default
      config:
        - subnet: ${MACVLAN_NETWORK_SUBNET}
          gateway: ${MACVLAN_NETWORK_GATEWAY}

services:
  adguard-home:
    container_name: adguard-home
    image: adguard/adguardhome:${ADGUARD_HOME_VERSION}
    restart: unless-stopped
    # As this container uses a MACVLAN network, ports do not need to be published.
    networks:
      adguard_home_network:
        ipv4_address: ${MACVLAN_NETWORK_IP}
    volumes:
      - ./config:/opt/adguardhome/conf
      - ./data:/opt/adguardhome/work/data
