networks:
  traefik_network:
    external: true

services:
  adguard-home:
    networks:
      traefik_network:
        interface_name: eth1
        gw_priority: 0
    expose:
      - 80
    labels:
      ## Traefik
      - traefik.enable=true
      # Router
      - traefik.http.routers.${ADGUARD_HOME_CONTAINER_NAME}.entrypoints=websecure
      - traefik.http.routers.${ADGUARD_HOME_CONTAINER_NAME}.rule=Host(`${ADGUARD_HOME_FQDN}`)
      # Service
      - traefik.http.services.${ADGUARD_HOME_CONTAINER_NAME}.loadbalancer.server.port=80
      ## Glance
      - glance.name=AdGuard Home
      # https://github.com/glanceapp/glance/blob/main/docs/configuration.md#icons
      - glance.icon=sh:adguard-home
      - glance.url=https://${ADGUARD_HOME_FQDN}
      - glance.description=Network-wide software for blocking ads & tracking.
      - glance.category=infrastructure
