networks:
  traefik_network:
    external: true

services:
  adguard-home:
    networks:
      - traefik_network
    expose:
      - 80
    labels:
      ## Traefik
      - traefik.enable=true
      # Router
      - traefik.http.routers.${ADGUARD_HOME_CONTAINER_NAME}.entrypoints=websecure
      - traefik.http.routers.${ADGUARD_HOME_CONTAINER_NAME}.rule=Host(`${ADGUARD_HOME_FQDN}`)
      # Service
      - traefik.http.services.${ADGUARD_HOME_CONTAINER_NAME}.loadbalancer.server.port=80
      ## Glance
      - glance.hide=false
      - glance.name=AdGuard Home
      - glance.icon=sh:adguard-home
      - glance.url=https://${ADGUARD_HOME_FQDN}
      - glance.description=AdGuard Home is a network-wide software for blocking ads & tracking.
      - glance.tags=network
