name: AdGuard Home

networks:
  adguard_home_network:
    name: adguard_home_network
    driver: macvlan
    driver_opts:
      parent: ${MACVLAN_NETWORK_INTERFACE}
    ipam:
      driver: default
      config:
        - subnet: ${MACVLAN_NETWORK_SUBNET}
          gateway: ${MACVLAN_NETWORK_GATEWAY}

  traefik_network:
    external: true

volumes:
  adguard_home_config:
    name: "adguard_home_config"
  adguard_home_data:
    name: "adguard_home_data"

services:
  adguard-home:
    container_name: adguard-home
    image: adguard/adguardhome:${ADGUARD_HOME_VERSION}
    restart: unless-stopped
    # As this container uses a MACVLAN network, ports do not need to be published.
    networks:
      adguard_home_network:
        ipv4_address: ${MACVLAN_NETWORK_IP}
      traefik_network:
    expose:
      - 80
    volumes:
      - adguard_home_config:/opt/adguardhome/conf
      - adguard_home_data:/opt/adguardhome/work/data
    labels:
      ## Traefik
      - traefik.enable=true
      # Router
      - traefik.http.routers.adguard-home.entrypoints=websecure
      - traefik.http.routers.adguard-home.rule=Host(`${ADGUARD_HOME_FQDN}`)
      # Service
      - traefik.http.services.adguard-home.loadbalancer.server.port=80
