name: AdGuard Home

services:
  adguard-home:
    container_name: ${ADGUARD_HOME_CONTAINER_NAME}
    hostname: ${ADGUARD_HOME_CONTAINER_NAME}
    image: adguard/adguardhome:${ADGUARD_HOME_IMAGE_VERSION}
    user: ${PUID}:${PGID}
    restart: unless-stopped
    network_mode: host
    volumes:
      - .docker/config:/opt/adguardhome/conf
      - .docker/data:/opt/adguardhome/work/data
