- name: Create and open LUKS encrypted device "{{ disk.name }}"
  community.crypto.luks_device:
    device: "{{ disk.device }}"
    state: opened
    name: "{{ disk.name }}"
    keyfile: "{{ disk.keyfile }}"
    allow_discards: true

- name: Check if "{{ disk.name }}" filesystem exists
  ansible.builtin.command:
    cmd: blkid /dev/mapper/{{ disk.name }}
  register: disk_has_fs
  failed_when: false
  changed_when: false

- name: Create ext4 filesystem on "{{ disk.name }}"
  community.general.filesystem:
    fstype: ext4
    dev: /dev/mapper/{{ disk.name }}
    opts: -L {{ disk.label }}
  when: disk_has_fs.rc != 0

- name: Add "{{ disk.name }}" to crypttab
  community.general.crypttab:
    name: "{{ disk.name }}"
    backing_device: "{{ disk.device }}"
    password: "{{ disk.keyfile }}"
    opts: luks,discard,x-initrd.attach
    state: present
  register: crypttab_update

- name: Mount "{{ disk.name }}" in fstab
  ansible.posix.mount:
    path: "{{ disk.mount }}"
    src: /dev/mapper/{{ disk.name }}
    fstype: ext4
    opts: defaults,noatime
    state: mounted

- name: Set fact if crypttab changed
  ansible.builtin.set_fact:
    disk_crypttab_changed: "{{ crypttab_update is changed }}"
