@startnwdiag common-diagram
!include <office/Devices/router>
!include <office/Servers/cluster_server>
!include <office/Servers/application_server>
!include <office/Servers/virtual_application_server>

nwdiag {
  network internal {
      address = "192.168.1.x/24"

      common [address = "192.168.1.2"];
  }

  common [description = "<$application_server>\n Common\n *.m3w.ch"]

  network host {
    common

    samba
    traefik
  }

  samba [description = "<$virtual_application_server>\n Samba\n (Network shares)\n smb://m3w.ch"]
  traefik [description = "<$virtual_application_server>\n Traefik\n (Reverse proxy)\n https://traefik.m3w.ch"];

  network traefik_network {
    address = "<Docker internal network>"
  
    glance
    qbittorrent
    traefik
    wg_easy
  }

  glance [description = "<$virtual_application_server>\n Glance\n (Dashboard)\n https://m3w.ch"]
  qbittorrent [description = "<$virtual_application_server>\n qBittorrent\n (Torrent client)\n https://qbittorrent.m3w.ch"]
  wg_easy [description = "<$virtual_application_server>\n Wireguard Easy\n (VPN)\n https://vpn.m3w.ch"]
}
@endnwdiag
