@startnwdiag legend
!include <office/Clouds/public_cloud>
!include <office/Devices/cell_phone_generic>
!include <office/Devices/device_laptop>
!include <office/Devices/device_tv>
!include <office/Devices/hard_disk>
!include <office/Devices/router>
!include <office/Devices/workstation>
!include <office/Servers/server_generic>
!include <office/Servers/virtual_application_server>

nwdiag {
    internet [description = "<$public_cloud>\n Internet"]
    router [description = "<$router>\n Router"]
    server [description = "<$server_generic>\n Server"]
    laptop [description = "<$device_laptop>\n Laptop"]
    console [description = "<$device_tv>\n Console"]
    workstation [description = "<$workstation>\n Workstation"]
    container [description = "<$virtual_application_server>\n Container"]
    storage [description = "<$hard_disk>\n Storage"]
    smartphone [description = "<$cell_phone_generic>\n Smartphone"]
}
@endnwdiag
