@startnwdiag m3w-architecture
!include <office/Concepts/application_generic>
!include <office/Clouds/public_cloud>
!include <office/Devices/cell_phone_generic>
!include <office/Devices/device_laptop>
!include <office/Devices/device_tv>
!include <office/Devices/hard_disk>
!include <office/Devices/router>
!include <office/Devices/workstation>
!include <office/Servers/application_server>
!include <office/Servers/server_generic>
!include <office/Servers/virtual_application_server>

<style>
legend {
  HorizontalAlignment center
  FontSize 12
}
</style>

title m3w.ch architecture

legend
  **Legend**
  <#transparent,#transparent>|   <$public_cloud>   |   <$router>   |   <$server_generic>   |   <$device_laptop>   |   <$device_tv>   |   <$workstation>   |   <$application_generic>   |   <$virtual_application_server>   |   <$hard_disk>   |   <$cell_phone_generic>   |
  |   Internet   |   Router   |   Server   |   Laptop   |   Console   |   Workstation   |   Application   |   Container   |   Storage   |   Smartphone   |
endlegend

nwdiag {
  internet [shape = cloud,  description = "<$public_cloud>\n**Internet**"]

  router [address = "<External IP>, :25565, :51820/udp, :52570/tcp+udp",  description = "<$router>\n**Yallo Fiber Box 2**\nyallo.m3w.ch"]

  nas [description = "<$server_generic>\n**NAS**\nnas.m3w.ch"]
  nas_1 [description = "<$server_generic><$hard_disk><$hard_disk>\n**NAS**\nStorage 18 TB + 2 TB"]

  framework [description = "<$device_laptop>\n**Framework**\nframework.m3w.ch"]
  macbook_pro [description = "<$device_laptop>\n**MacBook Pro**\nmacbook.m3w.ch"]
  nintendo_wii [description = "<$device_tv>\n**Nintendo Wii**\nwii.m3w.ch"]
  sony_ps5 [description = "<$device_tv>\n**Sony PlayStation 5**\nps5.m3w.ch"]
  libreelec [description = "<$workstation>\n**LibreELEC**\nkodi.m3w.ch"]
  raspberry_pi [description = "<$server_generic>\n**Raspberry Pi 3**\nraspberry.m3w.ch"]
  raspberry_pi_1 [description = "<$server_generic><$hard_disk>\n**Raspberry Pi 3 **\nStorage 8 GB"]

  adguard_home [description = "<$virtual_application_server>\n**AdGuard Home**\nDNS and DHCP server\nhttps://adguard.m3w.ch"]
  beszel [description = "<$virtual_application_server>\n**Beszel**\nHardware monitoring\nhttps://beszel.m3w.ch"]
  gatus [description = "<$virtual_application_server>\n**Gatus**\nSoftware monitoring\nhttps://gatus.m3w.ch"]
  glance [description = "<$virtual_application_server>\n**Glance**\nDashboard\nhttps://m3w.ch"]
  navidrome [description = "<$virtual_application_server>\n**Navidrome**\nMusic server\nhttps://navidrome.m3w.ch"]
  pocket_id [description = "<$virtual_application_server>\n**Pocket ID**\nAuthentification\nhttps://auth.m3w.ch"]
  qbittorrent [description = "<$virtual_application_server>\n**qBittorrent**\nTorrent client\nhttps://qbittorrent.m3w.ch"]
  resticprofile_debian [description = "<$virtual_application_server>\n**resticprofile (debian)**\nBackups"]
  resticprofile_heaspery [description = "<$virtual_application_server>\n**resticprofile (heaspery)**\nBackups"]
  resticprofile_ludelafo [description = "<$virtual_application_server>\n**resticprofile (ludelafo)**\nBackups"]
  samba [description = "<$virtual_application_server>\n**Samba**\nNetwork shares\nsmb://192.168.1.2"]
  syncthing_ludelafo [description = "<$virtual_application_server>\n**Syncthing (ludelafo)**\nFiles synchronization\nhttps://syncthing.ludelafo.m3w.ch"]
  syncthing_heaspery [description = "<$virtual_application_server>\n**Syncthing (heaspery)**\nFiles synchronization\nhttps://syncthing.heaspery.m3w.ch"]
  traefik [description = "<$virtual_application_server>\n**Traefik**\nReverse proxy\nhttps://traefik.m3w.ch"];
  wg_easy [description = "<$virtual_application_server>\n**Wireguard Easy**\nVPN\nhttps://vpn.m3w.ch"]
  tang [description = "<$application_generic>\n**Tang**\nLUKS unlocker\nhttp://192.168.1.254"]

  group {
    description = "**Overview**"
  
    internet -- router

    nas
    framework
    macbook_pro
    nintendo_wii
    sony_ps5
    libreelec
    raspberry_pi
  }

  group {
    description = "**Raspberry Pi**"

    raspberry_pi_1

    tang
  }
  
  group {
    description = "**NAS**"

    nas_1

    adguard_home
    beszel
    gatus
    glance
    navidrome
    pocket_id
    qbittorrent
    resticprofile_debian
    resticprofile_heaspery
    resticprofile_ludelafo
    samba
    syncthing_ludelafo
    syncthing_heaspery
    traefik
    wg_easy
  }

  // Overview
  network internal {
      address = "192.168.1.x/24"
      color = "LightGreen"
      router [address = "192.168.1.1"]

      nas [address = "192.168.1.2"]
      framework [address = "192.168.1.3"]
      macbook_pro [address = "192.168.1.4"]
  }

  network internal {
      address = "192.168.1.x/24"
      color = "LightGreen"

      nintendo_wii [address = "192.168.1.7"]
      sony_ps5 [address = "192.168.1.8"]
      libreelec [address = "192.168.1.9"]
  }

  network internal {
      address = "192.168.1.x/24"
      color = "LightGreen"

      raspberry_pi [address = "192.168.1.254"]
  }

  // Raspberry Pi
  network host {
    color = "LightSkyBlue"
    raspberry_pi_1

    tang
  }

  // NAS
  network host {
    color = "LightPink"
    nas_1

    adguard_home [address = ":53/tcp+udp, :67/udp, :68/udp, ..."]
    samba [address = ":445, ..."]
  }

  network host {
    color = "LightPink"
  
    resticprofile_debian
    resticprofile_heaspery
    resticprofile_ludelafo
  }

  network host {
    color = "LightPink"
  
    traefik [address = ":80, :443"]
  }

  network traefik_network {
    address = "<Docker internal network>"
    color = "LightSalmon"

    traefik
    beszel
    pocket_id
    wg_easy
  }

  network traefik_network {
    address = "<Docker internal network>"
    color = "LightSalmon"

    gatus
    glance
    navidrome
  }

  network traefik_network {
    address = "<Docker internal network>"
    color = "LightSalmon"

    qbittorrent
    syncthing_ludelafo
    syncthing_heaspery
  }
}
@endnwdiag
