@startnwdiag m3w-architecture
!include <office/Concepts/application_generic>
!include <office/Clouds/public_cloud>
!include <office/Devices/cell_phone_generic>
!include <office/Devices/device_laptop>
!include <office/Devices/device_tv>
!include <office/Devices/hard_disk>
!include <office/Devices/router>
!include <office/Devices/workstation>
!include <office/Servers/application_server>
!include <office/Servers/server_generic>
!include <office/Servers/virtual_application_server>
!include <office/Users/user>

<style>
legend {
  HorizontalAlignment center
  FontSize 12
}
</style>

title m3w.ch architecture

legend
  **Legend**
  <#transparent,#transparent>|   <$public_cloud>   |   <$router>   |   <$server_generic>   |   <$device_laptop>   |   <$device_tv>   |   <$workstation>   |   <$application_generic>   |   <$virtual_application_server>   |   <$hard_disk>   |   <$cell_phone_generic>   |   <$user>   |
  |   Internet   |   Router   |   Server   |   Laptop   |   Console   |   Workstation   |   Application   |   Container   |   Storage   |   Smartphone   |   User  |
endlegend

nwdiag {
  ' Infrastructure
  internet [shape = cloud,  description = "<$public_cloud>, **Internet**"]

  router [address = "<External IP>, :25565, :51820/udp, :52570/tcp+udp", description = "<$router>, **Yallo Fiber Box 2**, yallo.m3w.ch"]

  ' Users
  alpine [description = "<$user>, **alpine**, doas"]
  debian [description = "<$user>, **debian**, sudo + users"]
  ludelafo [description = "<$user>, **ludelafo**, users"]
  heaspery [description = "<$user>, **heaspery**, users"]

  ' Devices
  nas [description = "<$server_generic>, **NAS**, nas.m3w.ch"]
  nas_1 [description = "<$server_generic><$hard_disk><$hard_disk>, **NAS**, Storage 18 TB + 2 TB"]

  framework [description = "<$device_laptop>, **Framework**, framework.m3w.ch"]
  macbook_pro [description = "<$device_laptop>, **MacBook Pro**, macbook.m3w.ch"]
  nintendo_wii [description = "<$device_tv>, **Nintendo Wii**, wii.m3w.ch"]
  sony_ps5 [description = "<$device_tv>, **Sony PlayStation 5**, ps5.m3w.ch"]
  libreelec [description = "<$workstation>, **LibreELEC**, kodi.m3w.ch"]
  raspberry_pi [description = "<$server_generic>, **Raspberry Pi 3**, raspberry.m3w.ch"]
  raspberry_pi_1 [description = "<$server_generic><$hard_disk>, **Raspberry Pi 3**, Storage 8 GB"]

  ' Services
  adguard_home [description = "<$virtual_application_server>, **AdGuard Home**, DNS and DHCP server, https://adguard.m3w.ch"]
  beszel [description = "<$virtual_application_server>, **Beszel**, Hardware monitoring, https://beszel.m3w.ch"]
  gatus [description = "<$virtual_application_server>, **Gatus**, Software monitoring, https://gatus.m3w.ch"]
  glance [description = "<$virtual_application_server>, **Glance**, Dashboard, https://m3w.ch"]
  navidrome [description = "<$virtual_application_server>, **Navidrome**, Music server, https://navidrome.m3w.ch"]
  pocket_id [description = "<$virtual_application_server>, **Pocket ID**, Authentification, https://auth.m3w.ch"]
  qbittorrent [description = "<$virtual_application_server>, **qBittorrent**, Torrent client, https://qbittorrent.m3w.ch"]
  resticprofile_debian [description = "<$virtual_application_server>, **resticprofile (debian)**, Backups"]
  resticprofile_heaspery [description = "<$virtual_application_server>, **resticprofile (heaspery)**, Backups"]
  resticprofile_ludelafo [description = "<$virtual_application_server>, **resticprofile (ludelafo)**, Backups"]
  samba [description = "<$virtual_application_server>, **Samba**, Network shares, smb://192.168.1.2"]
  syncthing_ludelafo [description = "<$virtual_application_server>, **Syncthing (ludelafo)**, Files synchronization, https://syncthing.ludelafo.m3w.ch"]
  syncthing_heaspery [description = "<$virtual_application_server>, **Syncthing (heaspery)**, Files synchronization, https://syncthing.heaspery.m3w.ch"]
  traefik [description = "<$virtual_application_server>, **Traefik**, Reverse proxy, https://traefik.m3w.ch"];
  wg_easy [description = "<$virtual_application_server>, **Wireguard Easy**, VPN, https://vpn.m3w.ch"]
  tang [description = "<$application_generic>, **Tang**, LUKS unlocker, http://192.168.1.254"]

  group {
    description = "**Overview**"
  
    internet -- router

    nas
    framework
    macbook_pro
    nintendo_wii
    sony_ps5
    libreelec
    raspberry_pi
  }

  group {
    description = "**Raspberry Pi**"
    alpine

    raspberry_pi_1

    tang
  }
  
  group {
    description = "**NAS**"
    debian
    ludelafo
    heaspery

    nas_1

    adguard_home
    beszel
    gatus
    glance
    navidrome
    pocket_id
    qbittorrent
    resticprofile_debian
    resticprofile_heaspery
    resticprofile_ludelafo
    samba
    syncthing_ludelafo
    syncthing_heaspery
    traefik
    wg_easy
  }

  // Overview
  network internal {
      address = "192.168.1.x/24"
      color = "LightGreen"
      router [address = "192.168.1.1"]

      nas [address = "192.168.1.2"]
      framework [address = "192.168.1.3"]
      macbook_pro [address = "192.168.1.4"]
  }

  network internal {
      address = "192.168.1.x/24"
      color = "LightGreen"

      nintendo_wii [address = "192.168.1.7"]
      sony_ps5 [address = "192.168.1.8"]
      libreelec [address = "192.168.1.9"]
  }

  network internal {
      address = "192.168.1.x/24"
      color = "LightGreen"

      raspberry_pi [address = "192.168.1.254"]
  }

  // Raspberry Pi
  network host {
    color = "LightSkyBlue"

    alpine

    raspberry_pi_1

    tang
  }

  // NAS
  network host {
    color = "LightPink"

    debian
    ludelafo
    heaspery
  }

  network host {
    color = "LightPink"

    nas_1

    adguard_home [address = ":53/tcp+udp, :67/udp, :68/udp, ..."]
    samba [address = ":445, ..."]
  }

  network host {
    color = "LightPink"
  
    resticprofile_debian
    resticprofile_heaspery
    resticprofile_ludelafo
  }

  network host {
    color = "LightPink"
  
    traefik [address = ":80, :443"]
  }

  network traefik_network {
    address = "<Docker internal network>"
    color = "LightSalmon"

    traefik
    beszel
    pocket_id
    wg_easy
  }

  network traefik_network {
    address = "<Docker internal network>"
    color = "LightSalmon"

    gatus
    glance
    navidrome
  }

  network traefik_network {
    address = "<Docker internal network>"
    color = "LightSalmon"

    qbittorrent
    syncthing_ludelafo
    syncthing_heaspery
  }
}
@endnwdiag
