@startnwdiag
!include <office/Devices/router>
!include <office/Servers/cluster_server>
!include <office/Servers/application_server>

nwdiag {
  router [address = "192.168.1.1", description = "<$router>\n Yallo Fiber Box\n router.m3w.ch"]

  proxmox [description = "<$cluster_server>\n Proxmox\n proxmox.m3w.ch"]

  common [description = "<$application_server>\n Common\n *.m3w.ch"]
  ludovic [description = "<$application_server>\n Ludovic\n *.l.m3w.ch"]
  mathilde [description = "<$application_server>\n Mathilde\n *.m.m3w.ch"]

  router -- proxmox

  network internal {
      address = "192.168.1.x/24"

      proxmox [address = "192.168.1.10"]

      common [address = "192.168.1.2"]
      ludovic [address = "192.168.1.3"]
      mathilde [address = "192.168.1.4"]
  }
}
@endnwdiag
