networks:
  traefik_network:
    external: true

services:
  syncthing:
    networks:
      - traefik_network
    expose:
      - 8384
    ports: !override
      - 22000:22000
      - 22000:22000/udp
      - 21027:21027/udp
    labels:
      ## Traefik
      - traefik.enable=true
      # Router
      - traefik.http.routers.${SYNCTHING_CONTAINER_NAME}.entryPoints=websecure
      - traefik.http.routers.${SYNCTHING_CONTAINER_NAME}.rule=Host(`${SYNCTHING_FQDN}`)
      # Service
      - traefik.http.services.${SYNCTHING_CONTAINER_NAME}.loadbalancer.server.port=8384
      ## Glance
      - glance.hide=false
      - glance.name=Syncthing
      - glance.icon=sh:syncthing
      - glance.url=https://${SYNCTHING_FQDN}
      - glance.description=Syncthing is an open-source continuous file synchronization program.
      - glance.category=network
