# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    label: System
    cpu: true
    memory: true
    cputemp: true
    uptime: true
    units: metric

- resources:
    label: Storage
    expanded: true
    disk: /
