## Authelia configuration file
# https://github.com/authelia/authelia/blob/v4.39.20/config.template.yml
theme: "auto"
default_2fa_method: "totp"

## Authentication Backend
# https://www.authelia.com/configuration/first-factor/introduction/
# https://www.authelia.com/configuration/first-factor/ldap/
# https://www.authelia.com/integration/ldap/lldap/
authentication_backend:
  refresh_interval: "5m"
  password_reset:
    disable: false
  ldap:
    address: "ldap://lldap:3890"
    implementation: "lldap"
    base_dn: "dc=m3w,dc=ch"
    users_filter: "(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))"
    groups_filter: "(&(member={dn})(objectClass=groupOfNames))"
    user: "UID=authelia,OU=people,DC=m3w,DC=ch"

## TOTP
# https://www.authelia.com/configuration/second-factor/time-based-one-time-password/
# https://www.authelia.com/reference/integrations/time-based-one-time-password-apps/
totp:
  issuer: "auth.m3w.ch"

## Access Control
# https://www.authelia.com/configuration/security/access-control/
access_control:
  default_policy: "deny"
  rules:
    - domain: "whoami.m3w.ch"
      policy: "one_factor"
      subject:
        - ["group:ludelafo"]

## Regulation
# https://www.authelia.com/configuration/security/regulation/
regulation:
  modes:
    - "user"
    # - 'ip'
  max_retries: 3
  find_time: "2 minutes"
  ban_time: "5 minutes"

## Password policy
# https://www.authelia.com/configuration/security/password-policy/
password_policy:
  standard:
    enabled: true
    min_length: 12

## Identity Validation
# https://www.authelia.com/configuration/identity-validation/introduction/
# https://www.authelia.com/configuration/identity-validation/reset-password/
# https://www.authelia.com/configuration/identity-validation/elevated-session/
identity_validation:
  elevated_session:
    code_lifespan: "5 minutes"
    elevation_lifespan: "10 minutes"
    characters: 12

## https://www.authelia.com/configuration/session/introduction/
session:
  name: "authelia_session"
  same_site: "lax"
  inactivity: "5 minutes"
  expiration: "1 hour"
  remember_me: "1 month"
  cookies:
    - domain: "m3w.ch"
      authelia_url: "https://auth.m3w.ch"
      default_redirection_url: "https://m3w.ch"

## Storage
# https://www.authelia.com/configuration/storage/introduction/
# https://www.authelia.com/configuration/storage/sqlite/
storage:
  local:
    path: "/config/db.sqlite3"

## Notifications
# https://www.authelia.com/configuration/notifications/introduction/
# https://www.authelia.com/configuration/notifications/file/
notifier:
  filesystem:
    filename: "/config/notification.txt"

## Server
# https://www.authelia.com/configuration/miscellaneous/server/
server:
  address: "tcp://:9091"

## Log
# https://www.authelia.com/configuration/miscellaneous/logging/
log:
  level: "info"

## Identity Providers
# https://www.authelia.com/configuration/identity-providers/introduction/
# https://www.authelia.com/configuration/identity-providers/openid-connect/clients/
# https://www.authelia.com/configuration/identity-providers/openid-connect/provider/#key
# https://www.authelia.com/integration/openid-connect/frequently-asked-questions/#how-do-i-generate-a-client-identifier-or-client-secret
# https://www.authelia.com/reference/guides/generating-secure-values/
# https://www.authelia.com/reference/cli/authelia/authelia_crypto_pair_ed25519_generate/
identity_providers:
  oidc:
    jwks:
      # `docker run --rm --user "$(id -u):$(id -g)" --volume "$(pwd)/config:/config" authelia/authelia:4 authelia crypto pair rsa generate --directory /config`
      # prettier-ignore
      - key: {{ secret "/config/private.pem" | mindent 10 "|" | msquote }}
    clients:
      - client_name: "Beszel"
        # `docker run --rm authelia/authelia:4 authelia crypto rand --length 72 --charset rfc3986`
        client_id: "wGOloVbG2s0CDmvmBNXesm2B-I5uMMBaCVh5OpdXqrD-2gCSoiOai3mVd8ga6vQmE6_jPpba"
        # `docker run --rm authelia/authelia:4 authelia crypto hash generate pbkdf2 --variant sha512 --random --random.length 72 --random.charset rfc3986`
        client_secret: "$pbkdf2-sha512$310000$8K7qCDXhQpVj1lQD63lgNg$orzAcP7soKnKW.98VAXZRuvJr88hKInU1rawMlXQMLwmhsFbKhd9sH6PCAzXBWKOzmIIMSPsssXEpIJ7bIHGjQ"
        public: false
        authorization_policy: "one_factor"
        require_pkce: true
        pkce_challenge_method: "S256"
        redirect_uris:
          - "https://beszel.m3w.ch/api/oauth2-redirect"
        scopes:
          - "openid"
          - "email"
          - "profile"
        response_types:
          - "code"
        grant_types:
          - "authorization_code"
        access_token_signed_response_alg: "none"
        userinfo_signed_response_alg: "none"
        token_endpoint_auth_method: "client_secret_basic"
