networks:
  traefik_network:
    external: true

services:
  glance:
    networks:
      - traefik_network
    expose:
      - 8080
    ports: !reset []
    labels:
      ## Traefik
      - traefik.enable=true
      # Router
      - traefik.http.routers.${GLANCE_CONTAINER_NAME}.entryPoints=websecure
      - traefik.http.routers.${GLANCE_CONTAINER_NAME}.rule=Host(`${GLANCE_FQDN}`)
      # Service
      - traefik.http.services.${GLANCE_CONTAINER_NAME}.loadbalancer.server.port=8080
