name: whoami-2

services:
  whoami-2:
    container_name: ${WHOAMI_2_CONTAINER_NAME}
    hostname: ${WHOAMI_2_CONTAINER_NAME}
    image: traefik/whoami-2:${WHOAMI_2_IMAGE_VERSION}
    restart: unless-stopped
    ports:
      - 8080:80
